### ISSUE TITLE
Adopt Rubocop

### ISSUE THREAD

**Issue by danirod** [makigas/makigas#162]
Rubocop is installed but not in use. It should be adopted and the source code base should be linted.

## Subtasks

- [ ] Find a good .rubocop.yml in use in a big project that is successful.
- [ ] Add it to the repository.
- [ ] See what changes should be done in the source code and decide whether to format the code at the moment or to do it gradually.
