### ISSUE TITLE
Remove v5 templates

### ISSUE THREAD

**Issue by danirod** [makigas/makigas#673]
At the moment it is still necessary to enable the v6 feature flag by exporting `USE_SIX` environment variable to something before starting the Rails server. Now that v6 has been released and that it works, it should be good to delete the old code and keep only the new code.

This is not as easy to achieve as it can be imagined because the E2E feature tests will break, since it is designed after the v5 version, so the E2E tests have to be refactored as the old code is being removed from these templates.

Checklist:
- [x] Remove the `else` block that appears on all the `<% if ENV["USE_SIX"].present? %>` blocks in the app/views directory.
- [x] These refactors will break the E2E tests. Rewrite the tests to use the new site layout. Maybe remove some tests that do not make sense. (Maybe it makes more sense to use ViewComponent tests for these details)
- [x] Remove the old assets from the asset pipeline. (Maybe once this is done I can reorganize the six assets)
